### ISSUE TITLE
Date line grid issues

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#122]
From `feature/new-grid-system` branch. 

Grid is being filled in along the date line but errors when selecting: 

![](https://api.monosnap.com/rpc/file/download?id=feghjoCkWRCsVd8Yk4koKLuv1AZIm5)

cc @danielfdsilva

**Comment by danielfdsilva** [comment]
When zoomed out you can see the world multiple times. The system tried to paint squares over all of them. Since we are limiting the bounds we can just paint the squares over one of the worlds and that solves the problem.

If we absolutely need to have the squares repeat on all worlds we need to use a different approach.
