### ISSUE TITLE
Redesign landing modal

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#148]
Couple ideas have come up about potential ways to improve the landing modal. We've implemented https://github.com/hotosm/oam-browser/issues/141, still need to implement typeahead on search https://github.com/hotosm/oam-browser/issues/51, but there are a couple other improvements that could be helpful. 

Goals: 
  - Make the browser an entry point to OAM. Instead of a separate landing page, integrate access of the components into the landing modal on the browser. 
  - integrate system stats - how many images, what's the latest image, coverage 

@ricardomestre other goals we want to list here before we move into potential new layouts? 

cc @dylanmoriarty @nbumbarger @danielfdsilva

**Comment by ricardomestre** [comment]
I would also like to see:

- More custom search suggestions (is this feasible and interesting enough)?
- Intro paragraph (an 'About' summary) with a read more button pointing to the 'About' modal

**Comment by DylanMoriarty** [comment]
A few thoughts on this,

- We're starting with a pretty clean & usable interface. Things are in places you'd expect them to be, and there aren't _too_ many options.

- Some folks will either kill the modal immediately out of habit or by accident.

So with that in mind, I think we don't need buttons that duplicate the tasks (searching the map, uploading data). Instead the landing modal can rather serve as a very brief introduction for someone who's never been there before without creating a dependency on it and encouraging users to learn where the tasks are on the interface.

<img width="842" alt="screenshot 2016-06-14 14 35 32" src="https://cloud.githubusercontent.com/assets/9341928/16054934/45bf08aa-323d-11e6-978a-c9ccbe215d48.png">

Here the information inside would be sparse- just a few lines that explain what OAM is. I'm not sure we even need to call out the 'about' there- if someone wants to know more, there's a clear information button at the top they can navigate to.

A few other thoughts:

- It might be fun to do a callout to one particular stat (like total imagery) here, and have a more in-depth stats modal tucked in the 'information' nav.

- If we want to add search presents, perhaps we tuck those in the search bar itself or the settings button right next to it.

- If our goal is to orient someone on what OAM can do, we can build a separate page that goes more in depth what sort of projects have been helped by OAM or highlighting some of it's functionality. Link it in the About or Information sections.

**Comment by smit1678** [comment]
@DylanMoriarty Couple thoughts to keep digging into this more: 

- One of the thinking was to start to bring the project together more, instead of having separate pages for information or functionality. The more we can make the landing modal actionable and not just a splash modal, the better. That is the challenge of a welcome modal -- it gets in the way. How do we make it more actionable and useful than it is? Is that just get rid of it or can we make quick actions more useful? 

- One value for having good clear actions on a landing modal is so someone new doesn't have to get oriented to filters, toggles, and search options.

**Comment by DylanMoriarty** [comment]
Following our meeting I put together a few comps but still feel like we didn't quite come to a consensus on how we're moving forward on this. I hope this helps clarify things!

## Goals

1 ) Consolidate the OAM project into the browser tool, so it's the most prominent item and accessible.

2 ) Educate our users on the functionality and additional components of the OAM browser

3 ) Make sure actionable tasks are obvious and easily accessed by both new and returning users

## Reasons against using a modal to achieve those goals

- It annoys returning users by preventing them from getting what they're there to do

- It annoys initial users by preventing them from exploring what they can do in the tool itself

- [Most folks will dismiss it out of habit](http://ux.stackexchange.com/questions/24339/are-there-any-studies-of-users-getting-jaded-of-dialog-requests) because most intro modals at present are from newspaper sites telling you to disable ad-block or from sites telling you to buy an item.

- It's difficult to find commonly used web map tools that use welcome modals. [google](https://www.google.com/maps), [overpassturbo](https://overpass-turbo.eu/), [mapbox studio](https://www.mapbox.com/studio/styles/devseed/cinkjcls4001g4umbnw2rmlvq/edit/), [osm](http://www.openstreetmap.org/), [opentreemap](https://www.opentreemap.org/thegreeningofdetroitstreemap/map/), etc. Granted, most of those sites rely on previous knowledge or previous screens to inform the user of their purpose. 

- [Welcome modals are almost exclusively used as registration or onboarding slideshows](http://firsttimeux.tumblr.com/). They serve one function by focusing the user on a singular critical action.  If we were directing users to specifically browse, or specifically to upload imagery, or specifically learn about OAM, then I think this would make sense. However, we're trying to teach our user _about all the above_, and at that point the modal stops being the most productive means of achieving that goal. We either do a poor job of accurately describing those tasks, or make the modal too heavy.

I put together a mockup for a potential modal:

<img width="847" alt="screenshot 2016-06-16 02 15 13" src="https://cloud.githubusercontent.com/assets/9341928/16107126/31f8cef6-3368-11e6-8cc1-2170dd71acca.png">

but still feel it isn't the best way to achieve our goals. It's impossible to provide actionable links out to the functionality without duplicity- and if we provide unique functionality (i.e. the show latest imagery), there needs to be a way to retrieve the welcome menu so people can access that again. With that in mind and all of the above I think the question becomes moreso:

## What does OpenAerialMap.org look like?
 
Using the tool as the homepage could be fine as is:

- If we have the page just be the tool, the 'quick actions' just become the site's functionality. We have our search at the top left corner, we have upload & information at the top right, and we have a map we can pan/zoom around in the center. These are pretty common map patterns, and will likely be understood. It's not guided, but there also _aren't that many tasks you can perform_.

- Where are our users coming from? I imagine most folks will not be finding OAM accidentally. It has a very specific audience. Most links out to OAM will be from twitter accounts focused on sat/drone imagery, or blog posts associated with it. Essentially, few will be coming to the site entirely blind.

## Next Steps

I'm going to ask around and test in house to see what sort of troubles folks run into using the tool as is. Will post results later tomorrow (later today). I think we really need to nail this down because I'm still a little unsure: "One of the thinking was to start to bring the project together more, instead of having separate pages for information or functionality"- besides the landing page what would these other pages be?

**Q**: One thing I noticed mentioned in #42 were a few additional tools based on OAM. If we want to consolidate these into the browser, perhaps we should consider a more traditional header for the site? If we're linking from the browser, where will the links out to those tools exist?

**Q**: What information do we want to show on the site that isn't currently there? Stats have come up a few times in our discussions as well as a revamp of the about modal.

**Comment by smit1678** [comment]
> I'm going to ask around and test in house to see what sort of troubles folks run into using the tool as is. 

Ok great. 

> Q: One thing I noticed mentioned in #42 were a few additional tools based on OAM. If we want to consolidate these into the browser, perhaps we should consider a more traditional header for the site? If we're linking from the browser, where will the links out to those tools exist?

I think the future it may be helpful to start to bring the Uploader into the browser. Instead of the Uploader form being a separate single page app, it's integrated into the browser. The upload API and admin console will be separate. 

> Q: What information do we want to show on the site that isn't currently there? Stats have come up a few times in our discussions as well as a revamp of the about modal.

Yeah, stats is something we should definitely integrate and is one of the goals for redesigning the modal.

**Comment by DylanMoriarty** [comment]
We decided to build a separate landing page. Discussion continued in #154.
