### ISSUE TITLE
Double click should always zoom

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-browser#185]
When the TMS is active (and the detail modal is already highlighting a single image), double-clicking activates the detail modal and shows available images.

**Comment by mojodna** [comment]
(This does not happen when the thumbnail is active.)

**Comment by danielfdsilva** [comment]
We need to capture the click event on the map to be able to select the appropriate cell.
Apparently adding a click event listener to a layer blocks the propagation of the double click to the map.

This appears to be a limitation of leaflet itself. Instead of checking if a double click is going to happen it just fires the click event.

This can be hacked with timeouts to check for the double clicks, but the easiest option would be to disable double click altogether and make the behavior consistent. The scroll zoom and the zoom buttons would still available.

**Comment by danielfdsilva** [comment]
@smit1678 @mojodna Would disabling double click zoom be ok for you?

**Comment by smit1678** [comment]
@danielfdsilva If we disable double click, does the grid still get deselected if you have a cell already selected?

**Comment by danielfdsilva** [comment]
@smit1678 We don't have any interaction on double click right now, so nothing would really change.

**Comment by mojodna** [comment]
If double click does anything that isn't zooming, I think it's going to be irritating. Personally, I hate scroll to zoom (but I recognize that I'm an outlier) and needing to move to the buttons is similarly tedious.
