### ISSUE TITLE
Support deeper zooming

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-browser#200]
When browsing TMSes, the max zoom is currently capped at z18. When imagery is ~5cm, z22 is reasonable: http://tiles.openaerialmap.org/588d32222be03d001038e386/0/ca7d8e23-2994-41ce-8466-c32ba20e1248/preview#22/47.59043/-122.22537

**Comment by smit1678** [comment]
I'm behind this and I don't think there is any reason to restrict at this point, right? In the past, the previous TMSs that were generated from the Tiler were at lower zoom levels.

**Comment by mojodna** [comment]
Right, those maxed out at z18

**Comment by tombh** [comment]
I've done a bit of research on this and from what I can see, the public tiling servers that we use, namely mapbox and OSM, only have guaranteed global coverage for zoom level 18. There are occasionally tiles for z19 but very rarely more. This is just to explain the reason for hard limit at z18.

Of course OAM's tiles can go deeper, so I think the question now become how do give a sensible user experience for both maximum zoom levels? Currently if you override the zoom level, leaflet lets you zoom but just doesn't even attempt to make any HTTP requests for tiles at levels higher than z18. This means we can zoom in OAM tiles but the background map just goes blank, it completely disappears.

One idea could be to artificially zoom the global map imagery so it goes blurry. That's ugly but at least some kind of solution. Though I'm not exactly sure if it's even possible.

Another solution would be to have some rather complicated code that kept careful watch over what was currently in the browser viewport and automatically adjusted both the zoom level (zooming out if there's no OAM tiles) and the controls (re-enabling the "+" zoom in button when a OAM tile is in view).

Or of course we can just enable z22 across the globe, which means you might get a bit lost in the blankness for a while.

**Comment by smit1678** [comment]
@tombh Great summary of where we are at, thanks. Couple ideas: 

  * Implement z22 across the board, but limit panning and zooming to the bounding box of the image you have selected. Maybe that's overkill but it would limit the risk of getting lost when you have an image selected and at higher zoom levels. 

  * Look to build out the TMS preview page more and send users there for now to browse higher zoom levels. Example: http://tiles.openaerialmap.org/58ebc54fcfbcc90010aca44d/0/c44a3159-4c49-4278-874a-49845a1e8352/preview#18/49.56948/18.89199. Or do we look to change how the TMS functionality is interacted with on map.openaerialmap.org?

**Comment by mojodna** [comment]
On the Leaflet end of things, you can override the zoom per-layer (rather than for the map as a whole). I think that ends up overzooming layers that don't have better imagery available. Mapbox and OAM both have TileJSON endpoints (e.g. http://tiles.openaerialmap.org/58ebc54fcfbcc90010aca44d/0/c44a3159-4c49-4278-874a-49845a1e8352) that surface which zooms are available from them.

**Comment by tombh** [comment]
@mojodna That's great that you can override the zoom for individual layers, that'll definitely come in useful. If I understand right, the mapbox JS actually uses the zoom levels from the TileJSON to decide the maximum zoom level of the map, something like: the map's maximum zoom is the minimum of the user-specified max zoom and the layer's max zoom. Curiously `production.js` in this repo sets the max zoom to `undefined`, which I assume is a reference to mapbox's ability to use the zoom levels from individual layers' TileJSON manifest?

@smit1678 Interesting suggestions Nate. About sending the users out to the preview page, that made me think, well what's the difference between the preview page and the browser anyway? I think it's merely the fact that it's a separate UI - which then justifies the precedent for enforcing different zoom and pan levels. I imagine the user thinks something like, "ok I'm somewhere else, so that's understandable that the controls do something else."

That got me thinking, well what could we do to make the preview UI perfect. Well first thing would be to create a hard restriction on panning and the minimum zoom level - both panning and zooming out too far get you lost. As I said, merely the change in UI circumvents the cognitive dissonance of, "eh?? why's it behaving differently now??" So, what I'm wondering is, can we not do exactly this all *inside* the browser UI? The proviso being that we clearly trigger a small UI change to accompany the change of rules. For instance, assuming you've arrived at some imagery through the modal dialog so that you have the individual summary open on the right - what if you then slightly coloured various elements of the UI in a consistent and coherent way;
  * give the imagery modal dialog background and/or borders a suitably subtle but noticeable shade of blue (indicates the "something's different now" mindset).
  * the zoom controls receive the exact same colour to borders/background and receive new max/min levels and also change the point at which they grey out becoming disabled.
  * the entire window gets a slight blue border indicating that panning has new restrictions, namely you can't pan such that for example, the imagery's western extremity can leave the left hand side of the screen.

One problem with that is how you would enter this new UI state without going through the imagery modal? Maybe it could be triggered when you are both at zoom 18 _and_ a portion of imagery intersects with the viewport?

**Comment by tombh** [comment]
Oh wow, I only just realised, imagery *only* appears when the preview modal is open! This means it's trivial to adjust zoom and probably panning as well, when a single piece of imagery is selected.

Ok so that change things a bit. It would be a relatively straight forward fix here, without having to do any fancy UI state hinting. What I propose is simply that zoom is increased to 22 *only* when a single piece of imagery is selected.

One question though, what should the behaviour be when the user is zoomed in beyond 18 and they close they deselect the current imagery? To zoom back out to 18, centred on the same coords? I think that's ok, a tiny bit sudden and jarring, but ok.

**Comment by smit1678** [comment]
> One question though, what should the behaviour be when the user is zoomed in beyond 18 and they deselect the current imagery? To zoom back out to 18, centred on the same coords? I think that's ok, a tiny bit sudden and jarring, but ok.

@tombh Let's try that out and see how it feels. I think that might be ok but curious of how the performance is, but the might be handled ok with how we use the loading icon.

**Comment by tombh** [comment]
Reopening to track a fix to use `https` for tile endpoints by default. The fix is currently on the develop branch and ready for testing.

**Comment by smit1678** [comment]
@tombh Did this change during the refactor? It looks like this isn't working now on the new work. Or can you point to where someone should be looking to debug this? We're using a new database on staging so it's not the TMS prefix path issue. 

![openaerialmap browser 2017-10-11 17-49-59](https://user-images.githubusercontent.com/796838/31428352-d2372bda-aead-11e7-954a-873c6fdfa96f.jpg)

**Comment by tombh** [comment]
This is the core function: https://github.com/hotosm/oam-browser/blob/oauth-login/src/components/map.js#L523

There is also a disabled test (waiting on running the dynamic tiler locally) for this exact feature: https://github.com/hotosm/oam-browser/blob/oauth-login/test/integration/general_test.js#L227
