### ISSUE TITLE
Add open preview button on browser

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#215]
It's great to view the TMS from within the map view together with its metadata, but sometimes it would be nice to have direct access to the Preview endpoint of tiles.openaerialmap.org. This is helpful for sharing the individual image. Zooming and panning is also more difficult within the browser because of the grid. 

Proposing an idea to add an open preview button in place of the download button. And then move the download button to below the metadata. 

Open to other ideas but first pass at a way we could implement: 

![](https://api.monosnap.com/rpc/file/download?id=1va5KKnKrdTe7DkQySt2bwbauL3p82)

**Comment by tombh** [comment]
I agree. Though I have a caveat in that this further promotes the fragmentation of OAM. Just one small example of this is that we then have an official responsibility to maintain the tile preview code, because it is no longer merely a hidden geek feature. It's not a lot of code, but nevertheless if we make the effort to integrate then in the long term it will benefit from free updates and maintenance.

**Comment by smit1678** [comment]
Agreed on the limiting maintenance. I think the larger goal - and why the preview code fills it - is the need to have a quick, shareable individual view of the specific image in slippy map form. Previewing the TMS within the view with the grid and side bar is the primary use, but having a specific easy to share endpoint will help get people to explore that image and then can be used to drive back to the map view to search more.

**Comment by tombh** [comment]
I definitely agree about the idea of having a quick URL for doing nothing more than exploring an individual image. I just want to push a little against separating that page out from the main site. For example what if we had a mode on the main site that hid all the controls to emphasise previewing? Then it would look almost identical to the current preview page. If that's not a good idea because the main site takes too long to load, then that's a different problem and it would be a shame to have our decision making process influenced by that. In an ideal world the canonical permalink for a piece of imagery should be underneath the main domain.
