### ISSUE TITLE
Blue grid on top of map when selecting imagery from Latest Uploads

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-browser#250]
When selecting an image from the front page, Latest Imagery, the TMS is rendered below the grid. 

![openaerialmap browser 2017-10-05 17-17-22](https://user-images.githubusercontent.com/796838/31211978-7ec067de-a9f1-11e7-8a22-d5a3ac6e4504.jpg)

But when selecting a grid square and clicking the same image, the grid is below the TMS. This should be the correct behavior. 

![openaerialmap browser 2017-10-05 17-21-23](https://user-images.githubusercontent.com/796838/31211994-a8c55cba-a9f1-11e7-8df8-2afe7440f08e.jpg)

**Comment by tombh** [comment]
I've spent a few hours on this already but just couldn't find a reliable way. I'm not sure why it stopped working in the first place. But the 2 methods in the docs are to change the temporal order of applying layers (more recent layers are put on the top) and using `zIndex` in JS and `zindex` in CSS didn't work. My suspicion is that the case here is different because it's a tileLayer over geoJSON, when usually it would be the other way around.

So far now, just to have a fix in place, I just remove the grid only when showing a single image.
