### ISSUE TITLE
Latest deployment breaks previous URLs

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#266]
This linked was shared a couple of weeks ago: `https://map.openaerialmap.org/#/-72.24601549919855,18.64219774452739,12/0322112030100/59bebf9646e19904aab0ae4a?_k=nv0j3h` but after the latest deployment, it doesn't seem to work anymore.
The corresponding new URL might be `https://map.openaerialmap.org/#/-72.29072570800781,18.60525215054155,10/square/032211203001/59bebf9646e19904aab0ae4a?_k=nv0j3h` but doesn't seem to work.

What is the new `/square/` parameter added to the URL?

**Comment by smit1678** [comment]
@cgiovando Square is the grid square that is selected. OAM urls have never been perfectly sharable since we've relied on a grid which is different per zoom. This will change again in the future as we adjust how the grid is shown. Were you able to find the image by searching and selecting a grid square (as opposed to clicking on an old url)?
