### ISSUE TITLE
Base layer switcher

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-browser#72]
Allow the user to switch between multiple pre-defined base layers and custom Web services (WMS, TMS, etc)

**Comment by smit1678** [comment]
@cgiovando What do you think is the use case for this? Can you explain more how and why a user might want this functionality?

**Comment by cgiovando** [comment]
As with many common Web maps the user may want to use different basemaps to drive the search or to provide context. For example, the user may want to display a "satellite" basemap (Bing, Mapbox or custom TMS/WMS) to compare and contextualize results displayed.

**Comment by smit1678** [comment]
Ok. We can think through the best implementation if core purpose is to drive search and comparison and not just add a layer switcher. 

Also saw that you tagged this as v2. I think this should be pushed to a later version since right now we're focused on core functionality and this would be an enhancement on top of core search.

**Comment by cgiovando** [comment]
I think a simple layer switcher (e.g. http://leafletjs.com/examples/layers-control.html) will do it for now, but if you think it'll take long to add we can discuss moving it to V3.

**Comment by smit1678** [comment]
To update here, this work is now tracked in #175
